version: "3"

services:
  overlay:
    image: puchuu/test-overlay_x86_64-unknown-linux-gnu:latest
    volumes:
      - gentoo-portage:/var/db/repos/gentoo
  portage:
    image: puchuu/test-portage:latest
    volumes:
      - gentoo-portage:/var/db/repos/gentoo

volumes:
  gentoo-portage:
