version: "3"

services:
  overlay:
    image: puchuu/test-overlay_x86_64-unknown-linux-gnu:latest
    entrypoint: ls -la /var/db/repos/gentoo/
    volumes:
      - .:/mnt/data
      - gentoo-portage:/var/db/repos/gentoo
  portage:
    image: puchuu/test_portage:latest
    entrypoint: /bin/true
    volumes:
      - gentoo-portage:/var/db/repos/gentoo

volumes:
  gentoo-portage:
