version: "3"

services:
  overlay:
    image: puchuu/test-compression_i686-gentoo-linux-musl:latest
    command: tail -f /dev/null
    volumes:
      - .:/mnt/data
      - gentoo-portage:/var/db/repos/gentoo
  portage:
    image: puchuu/test_portage:latest
    command: tail -f /dev/null
    volumes:
      - gentoo-portage:/var/db/repos/gentoo

volumes:
  gentoo-portage:
