name: test

on:
  - push

jobs:
  gentoo:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker compose
        run: docker-compose up -d
      - name: CI test
        run: docker-compose run overlay
